  CREATE TABLE "BRANCH" 
   (	"BRANCH_ID" NUMBER(6,0), 
	"BRANCH_NAME" VARCHAR2(100) NOT NULL ENABLE, 
	"ZONE" VARCHAR2(50) NOT NULL ENABLE, 
	"CONTACT_PHONE" VARCHAR2(20), 
	 CONSTRAINT "PK_BRANCH" PRIMARY KEY ("BRANCH_ID")
  USING INDEX  ENABLE
   ) ;

  CREATE TABLE "DEFAULTER_LOG" 
   (	"DEFAULT_ID" NUMBER(8,0), 
	"LOAN_ID" NUMBER(8,0) NOT NULL ENABLE, 
	"FLAGGED_DATE" DATE NOT NULL ENABLE, 
	"RESOLVED_DATE" DATE, 
	"STATUS" VARCHAR2(10) DEFAULT 'OPEN', 
	 CONSTRAINT "CK_DEFAULTLOG_STATUS" CHECK (status IN ('OPEN','RESOLVED')) ENABLE, 
	 CONSTRAINT "PK_DEFAULTLOG" PRIMARY KEY ("DEFAULT_ID")
  USING INDEX  ENABLE
   ) ;

  CREATE TABLE "GUARANTOR" 
   (	"GUARANTOR_ID" NUMBER(8,0), 
	"RIDER_ID" NUMBER(8,0) NOT NULL ENABLE, 
	"FIRST_NAME" VARCHAR2(50) NOT NULL ENABLE, 
	"LAST_NAME" VARCHAR2(50) NOT NULL ENABLE, 
	"NATIONAL_ID" VARCHAR2(20) NOT NULL ENABLE, 
	"PHONE" VARCHAR2(20) NOT NULL ENABLE, 
	"RELATIONSHIP_TO_RIDER" VARCHAR2(30), 
	 CONSTRAINT "PK_GUARANTOR" PRIMARY KEY ("GUARANTOR_ID")
  USING INDEX  ENABLE
   ) ;

  CREATE TABLE "LOAN_AGREEMENT" 
   (	"LOAN_ID" NUMBER(8,0), 
	"RIDER_ID" NUMBER(8,0) NOT NULL ENABLE, 
	"MOTORCYCLE_ID" NUMBER(8,0) NOT NULL ENABLE, 
	"LOAN_AMOUNT" NUMBER(12,2) NOT NULL ENABLE, 
	"INTEREST_RATE" NUMBER(5,2) NOT NULL ENABLE, 
	"REPAYMENT_FREQUENCY" VARCHAR2(10) NOT NULL ENABLE, 
	"START_DATE" DATE NOT NULL ENABLE, 
	"DURATION_MONTHS" NUMBER(3,0) NOT NULL ENABLE, 
	"STATUS" VARCHAR2(15) DEFAULT 'ACTIVE', 
	 CONSTRAINT "CK_LOAN_AMOUNT" CHECK (loan_amount > 0) ENABLE, 
	 CONSTRAINT "CK_LOAN_RATE" CHECK (interest_rate >= 0) ENABLE, 
	 CONSTRAINT "CK_LOAN_FREQ" CHECK (repayment_frequency IN ('DAILY','WEEKLY','MONTHLY')) ENABLE, 
	 CONSTRAINT "CK_LOAN_DURATION" CHECK (duration_months > 0) ENABLE, 
	 CONSTRAINT "CK_LOAN_STATUS" CHECK (status IN ('ACTIVE','DEFAULTED','CLEARED')) ENABLE, 
	 CONSTRAINT "PK_LOAN" PRIMARY KEY ("LOAN_ID")
  USING INDEX  ENABLE
   ) ;

  CREATE TABLE "MAINTENANCE_RECORD" 
   (	"MAINTENANCE_ID" NUMBER(8,0), 
	"MOTORCYCLE_ID" NUMBER(8,0) NOT NULL ENABLE, 
	"SERVICE_DATE" DATE NOT NULL ENABLE, 
	"DESCRIPTION" VARCHAR2(200), 
	"COST" NUMBER(10,2) NOT NULL ENABLE, 
	"GARAGE_NAME" VARCHAR2(80), 
	 CONSTRAINT "CK_MAINTENANCE_COST" CHECK (cost >= 0) ENABLE, 
	 CONSTRAINT "PK_MAINTENANCE" PRIMARY KEY ("MAINTENANCE_ID")
  USING INDEX  ENABLE
   ) ;

  CREATE TABLE "MOTORCYCLE" 
   (	"MOTORCYCLE_ID" NUMBER(8,0), 
	"BRANCH_ID" NUMBER(6,0) NOT NULL ENABLE, 
	"MAKE" VARCHAR2(40) NOT NULL ENABLE, 
	"MODEL" VARCHAR2(40) NOT NULL ENABLE, 
	"ENGINE_NO" VARCHAR2(30) NOT NULL ENABLE, 
	"VEHICLE_IDENTIFICATION_NUMBER" VARCHAR2(30) NOT NULL ENABLE, 
	"PURCHASE_PRICE" NUMBER(12,2) NOT NULL ENABLE, 
	"PURCHASE_DATE" DATE, 
	"STATUS" VARCHAR2(15) DEFAULT 'AVAILABLE', 
	 CONSTRAINT "CK_MOTORCYCLE_PRICE" CHECK (purchase_price > 0) ENABLE, 
	 CONSTRAINT "CK_MOTORCYCLE_STATUS" CHECK (status IN ('AVAILABLE','LEASED','REPOSSESSED')) ENABLE, 
	 CONSTRAINT "PK_MOTORCYCLE" PRIMARY KEY ("MOTORCYCLE_ID")
  USING INDEX  ENABLE, 
	 CONSTRAINT "UQ_MOTORCYCLE_ENGINE" UNIQUE ("ENGINE_NO")
  USING INDEX  ENABLE, 
	 CONSTRAINT "UQ_MOTORCYCLE_VIN" UNIQUE ("VEHICLE_IDENTIFICATION_NUMBER")
  USING INDEX  ENABLE
   ) ;

  CREATE TABLE "REPAYMENT" 
   (	"REPAYMENT_ID" NUMBER(10,0), 
	"SCHEDULE_ID" NUMBER(10,0) NOT NULL ENABLE, 
	"USER_ID" NUMBER(6,0) NOT NULL ENABLE, 
	"AMOUNT_PAID" NUMBER(10,2) NOT NULL ENABLE, 
	"PAYMENT_DATE" DATE DEFAULT SYSDATE, 
	 CONSTRAINT "CK_REPAYMENT_AMOUNT" CHECK (amount_paid > 0) ENABLE, 
	 CONSTRAINT "PK_REPAYMENT" PRIMARY KEY ("REPAYMENT_ID")
  USING INDEX  ENABLE
   ) ;

  CREATE TABLE "REPAYMENT_SCHEDULE" 
   (	"SCHEDULE_ID" NUMBER(10,0), 
	"LOAN_ID" NUMBER(8,0) NOT NULL ENABLE, 
	"DUE_DATE" DATE NOT NULL ENABLE, 
	"AMOUNT_DUE" NUMBER(10,2) NOT NULL ENABLE, 
	"STATUS" VARCHAR2(10) DEFAULT 'PENDING', 
	 CONSTRAINT "CK_SCHEDULE_AMOUNT" CHECK (amount_due > 0) ENABLE, 
	 CONSTRAINT "CK_SCHEDULE_STATUS" CHECK (status IN ('PENDING','PAID','MISSED')) ENABLE, 
	 CONSTRAINT "PK_SCHEDULE" PRIMARY KEY ("SCHEDULE_ID")
  USING INDEX  ENABLE
   ) ;

  CREATE TABLE "RIDER" 
   (	"RIDER_ID" NUMBER(8,0), 
	"BRANCH_ID" NUMBER(6,0) NOT NULL ENABLE, 
	"FIRST_NAME" VARCHAR2(50) NOT NULL ENABLE, 
	"LAST_NAME" VARCHAR2(50) NOT NULL ENABLE, 
	"NATIONAL_ID" VARCHAR2(20) NOT NULL ENABLE, 
	"PHONE" VARCHAR2(20) NOT NULL ENABLE, 
	"ADDRESS" VARCHAR2(150), 
	"DATE_REGISTERED" DATE DEFAULT SYSDATE, 
	"STATUS" VARCHAR2(15) DEFAULT 'ACTIVE', 
	 CONSTRAINT "CK_RIDER_STATUS" CHECK (status IN ('ACTIVE','SUSPENDED','CLEARED')) ENABLE, 
	 CONSTRAINT "PK_RIDER" PRIMARY KEY ("RIDER_ID")
  USING INDEX  ENABLE, 
	 CONSTRAINT "UQ_RIDER_NATID" UNIQUE ("NATIONAL_ID")
  USING INDEX  ENABLE
   ) ;

  CREATE TABLE "USERS" 
   (	"USER_ID" NUMBER(6,0), 
	"BRANCH_ID" NUMBER(6,0), 
	"FULL_NAME" VARCHAR2(80) NOT NULL ENABLE, 
	"ROLE" VARCHAR2(20) NOT NULL ENABLE, 
	"USERNAME" VARCHAR2(30) NOT NULL ENABLE, 
	"PASSWORD_HASH" VARCHAR2(200) NOT NULL ENABLE, 
	 CONSTRAINT "CK_USERS_ROLE" CHECK (role IN ('BRANCH_OFFICER','ADMIN','AUDITOR')) ENABLE, 
	 CONSTRAINT "PK_USERS" PRIMARY KEY ("USER_ID")
  USING INDEX  ENABLE, 
	 CONSTRAINT "UQ_USERS_USERNAME" UNIQUE ("USERNAME")
  USING INDEX  ENABLE
   ) ;


  CREATE UNIQUE INDEX "UQ_USERS_USERNAME" ON "USERS" ("USERNAME") 
  ;

  CREATE INDEX "IDX_LOAN_MOTORCYCLE" ON "LOAN_AGREEMENT" ("MOTORCYCLE_ID") 
  ;

  CREATE INDEX "IDX_DEFAULTLOG_LOAN" ON "DEFAULTER_LOG" ("LOAN_ID") 
  ;

  CREATE INDEX "IDX_MAINTENANCE_MOTORCYCLE" ON "MAINTENANCE_RECORD" ("MOTORCYCLE_ID") 
  ;

  CREATE UNIQUE INDEX "PK_DEFAULTLOG" ON "DEFAULTER_LOG" ("DEFAULT_ID") 
  ;

  CREATE UNIQUE INDEX "PK_RIDER" ON "RIDER" ("RIDER_ID") 
  ;

  CREATE UNIQUE INDEX "PK_REPAYMENT" ON "REPAYMENT" ("REPAYMENT_ID") 
  ;

  CREATE UNIQUE INDEX "PK_USERS" ON "USERS" ("USER_ID") 
  ;

  CREATE UNIQUE INDEX "UQ_RIDER_NATID" ON "RIDER" ("NATIONAL_ID") 
  ;

  CREATE UNIQUE INDEX "PK_LOAN" ON "LOAN_AGREEMENT" ("LOAN_ID") 
  ;

  CREATE INDEX "IDX_MOTORCYCLE_BRANCH" ON "MOTORCYCLE" ("BRANCH_ID") 
  ;

  CREATE INDEX "IDX_SCHEDULE_LOAN" ON "REPAYMENT_SCHEDULE" ("LOAN_ID") 
  ;

  CREATE INDEX "IDX_USERS_BRANCH" ON "USERS" ("BRANCH_ID") 
  ;

  CREATE UNIQUE INDEX "PK_MOTORCYCLE" ON "MOTORCYCLE" ("MOTORCYCLE_ID") 
  ;

  CREATE UNIQUE INDEX "PK_SCHEDULE" ON "REPAYMENT_SCHEDULE" ("SCHEDULE_ID") 
  ;

  CREATE INDEX "IDX_GUARANTOR_RIDER" ON "GUARANTOR" ("RIDER_ID") 
  ;

  CREATE UNIQUE INDEX "PK_BRANCH" ON "BRANCH" ("BRANCH_ID") 
  ;

  CREATE UNIQUE INDEX "PK_MAINTENANCE" ON "MAINTENANCE_RECORD" ("MAINTENANCE_ID") 
  ;

  CREATE INDEX "IDX_LOAN_RIDER" ON "LOAN_AGREEMENT" ("RIDER_ID") 
  ;

  CREATE INDEX "IDX_RIDER_BRANCH" ON "RIDER" ("BRANCH_ID") 
  ;

  CREATE INDEX "IDX_REPAYMENT_USER" ON "REPAYMENT" ("USER_ID") 
  ;

  CREATE UNIQUE INDEX "PK_GUARANTOR" ON "GUARANTOR" ("GUARANTOR_ID") 
  ;

  CREATE UNIQUE INDEX "UQ_MOTORCYCLE_VIN" ON "MOTORCYCLE" ("VEHICLE_IDENTIFICATION_NUMBER") 
  ;

  CREATE INDEX "IDX_REPAYMENT_SCHEDULE" ON "REPAYMENT" ("SCHEDULE_ID") 
  ;

  CREATE UNIQUE INDEX "UQ_MOTORCYCLE_ENGINE" ON "MOTORCYCLE" ("ENGINE_NO") 
  ;



   CREATE SEQUENCE  "SEQ_BRANCH"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 21 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL ;

   CREATE SEQUENCE  "SEQ_DEFAULTLOG"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 21 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL ;

   CREATE SEQUENCE  "SEQ_GUARANTOR"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 41 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL ;

   CREATE SEQUENCE  "SEQ_LOAN"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 41 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL ;

   CREATE SEQUENCE  "SEQ_MAINTENANCE"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 21 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL ;

   CREATE SEQUENCE  "SEQ_MOTORCYCLE"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 21 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL ;

   CREATE SEQUENCE  "SEQ_REPAYMENT"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 41 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL ;

   CREATE SEQUENCE  "SEQ_RIDER"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 41 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL ;

   CREATE SEQUENCE  "SEQ_SCHEDULE"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 21 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL ;

   CREATE SEQUENCE  "SEQ_USERS"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 21 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL ;

  CREATE OR REPLACE EDITIONABLE SYNONYM "MOTORCYCLES" FOR "MOTORCYCLE";

  CREATE OR REPLACE EDITIONABLE SYNONYM "RIDERS" FOR "RIDER";


  CREATE OR REPLACE FORCE EDITIONABLE VIEW "VW_ACTIVE_LOANS" ("LOAN_ID", "RIDER_NAME", "MAKE", "MODEL", "LOAN_AMOUNT", "STATUS") AS 
  SELECT l.loan_id, r.first_name || ' ' || r.last_name AS rider_name, 
       m.make, m.model, l.loan_amount, l.status 
FROM LOAN_AGREEMENT l 
JOIN RIDER r ON l.rider_id = r.rider_id 
JOIN MOTORCYCLE m ON l.motorcycle_id = m.motorcycle_id 
WHERE l.status = 'ACTIVE';

  CREATE OR REPLACE FORCE EDITIONABLE VIEW "VW_BRANCH_DEFAULT_SUMMARY" ("BRANCH_NAME", "DEFAULT_COUNT") AS 
  SELECT b.branch_name, COUNT(dl.default_id) AS default_count 
FROM BRANCH b 
JOIN RIDER r ON b.branch_id = r.branch_id 
JOIN LOAN_AGREEMENT l ON r.rider_id = l.rider_id 
JOIN DEFAULTER_LOG dl ON l.loan_id = dl.loan_id 
GROUP BY b.branch_name;




